# -*- coding: utf-8 -*-
"""Breakdown of top Data Science Skills - PieChart

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dMp8Q4df0iNxlnkcFqfJgirJSEz-z9Iu
"""

#Top Skills In Data Science

import csv
import re

# List of keywords to search for
keywords = ['SQL', 'Python', 'Big Data', 'AWS', 'ETL', 'Hadoop', 'Spark', 'Kafka', 'Data Warehousing',
            'Data Pipelines', 'Data Modeling', 'Java', 'Database Management', 'NoSQL', 'Airflow', 'Docker',
            'Kubernetes', 'Redshift', 'Snowflake', 'Data Integration', 'Excel', 'Tableau', 'Data Visualization',
            'Data Analysis', 'Dashboards', 'Reporting', 'Business Intelligence', 'Data Mining', 'Statistics',
            'Power BI', 'Data Cleansing', 'Data Interpretation', 'Google Analytics', 'Data Modelling',
            'Predictive Analytics', ' R ', 'Data Mapping', 'Machine Learning', 'Deep Learning', 'Natural Language Processing',
            'Predictive Modeling', 'Mathematical Modeling', 'TensorFlow', 'Keras', 'Computer Vision', 'Artificial Intelligence']

# Create a dictionary to store the keyword counts
keyword_counts = {keyword: 0 for keyword in keywords}

# Open the CSV file and iterate over each row
with open('FinalJobData.csv', newline='', encoding='utf-8') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        # Convert the text to lowercase and remove punctuation
        text = re.sub(r'[^\w\s]', '', row['Skills']).lower()
        
        # Count the occurrences of each keyword in the text
        for keyword in keywords:
            if keyword.lower() in text:
                keyword_counts[keyword] += 1

# Sort the keyword counts in descending order
sorted_counts = sorted(keyword_counts.items(), key=lambda x: x[1], reverse=True)


for keyword, count in sorted_counts:
    print(f'{keyword}: {count}')

#Pie Chart of Top 10 Skills

import pandas as pd
import plotly.express as px


df = pd.read_csv('FinalJobData.csv')

# Calculate the counts of each skill and select the top 10 skills
skill_counts = df['Skills'].str.split(',').explode().str.strip().value_counts().nlargest(10)

# Create a pie chart using Plotly Express
fig = px.pie(
    skill_counts,
    values=skill_counts.values,
    names=skill_counts.index,
    title='Top 10 Data Science Skills'
)


fig.show()

#Bar Chart of Top 10 Skills

import pandas as pd
import plotly.express as px

df = pd.read_csv('FinalJobData.csv')

# Calculate the counts of each skill and select the top 10 skills
skill_counts = df['Skills'].str.split(',').explode().str.strip().value_counts().nlargest(10)

skill_counts = skill_counts.rename_axis('Skills')

# Create a bar chart using Plotly Express

fig = px.bar(
    skill_counts,
    x=skill_counts.index,
    y=skill_counts.values,
    color=skill_counts.index,
    labels={'x':'Skills','y':'Count'}
)

# Center the chart title
fig.update_layout(
    title={
        'text': 'Top 10 Data Science Skills',
        'x': 0.5,
        'xanchor': 'center'
    }
)


fig.update_xaxes(title='Skills')
fig.update_yaxes(title='Count')
fig.update_layout(xaxis={'categoryorder':'total descending'})


fig.show()