# -*- coding: utf-8 -*-
"""CodeForIndeedCombined.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_nNwrpCiExtyk2Rkkgqo7wAZhn1-hStw
"""

import pandas as pd

# Read the CSV file into a Pandas dataframe, specifying the encoding
df = pd.read_csv('Indeed_Job_Data_Combined.csv', encoding='utf-8')

# Replace any special characters with a '-' between texts
df = df.replace('[^a-zA-Z0-9]', '-', regex=True)

# Remove any rows with missing values
df = df.dropna()