# -*- coding: utf-8 -*-
"""Code_For_dice_data_skills.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18GBSkl0pc64OhBBhcC6c2hkmMpoM_dnu
"""

import pandas as pd

# Read the CSV file into a Pandas dataframe
df = pd.read_csv('cleaned_dice_data_with_skills_cleaned.csv')

# Combine the state and city into a single 'location' column
df['location'] = df['city'] + ', ' + df['state']

# Drop the original 'city' and 'state' columns
df = df.drop(['city', 'state'], axis=1)

# Remove any rows with missing values
df = df.dropna()

# Write the cleaned data to a new CSV file
df.to_csv('dice_data_with_skills_cleaned.csv', index=False)

"""This line imports the pandas library, which is a popular library in Python for data manipulation and analysis.

This line reads a CSV file called 'cleaned_dice_data_with_skills_cleaned.csv' into a pandas dataframe called df.

This line concatenates the 'city' and 'state' columns in df into a new column called 'location', separated by a comma and space.

This line removes the 'city' and 'state' columns from df since they have been combined into the new 'location' column.

This line removes any rows in df that contain missing values (i.e. NaN values).

This line saves the cleaned data from df to a new CSV file called 'dice_data_with_skills_cleaned.csv', with the index column excluded.

In summary, this code reads a CSV file into a pandas dataframe, combines columns into a new column, removes unnecessary columns, removes rows with missing values, and saves the cleaned data to a new CSV file.

"""

import pandas as pd

# Load CSV file into a DataFrame
df = pd.read_csv('cleaned_dice_data_with_skills_cleaned.csv')

# Drop rows where 'Salary' is less than 40,000
df = df[df['Salary'].str.replace(',', '').str.extract(r'(\d+)', expand=False).fillna('0').astype(int) >= 40000]

# Convert 'Salary' column to 'Yearly Min' and 'Yearly Max' columns
df[['yearly min', 'yearly max']] = df['Salary'].str.replace(',', '').str.extract(r'(\d+)\D*(\d+)?', expand=True).astype(float).fillna(0)

# Drop unwanted columns
df = df.drop(columns=['Salary'])

# Save the updated DataFrame to a new CSV file
df.to_csv('jobs_updated1.csv', index=False)