# -*- coding: utf-8 -*-
"""FinalProject_PieChart_JobSites

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1X4eNsq3TzmHHZT5lUTWArdiPN9asxBRk
"""

#PIE CHART FOR JOB SITE BREAKDOWN

import pandas as pd
import plotly.express as px

# Read the CSV file into a DataFrame
df = pd.read_csv('FinalJobData.csv')

# Calculate the counts of each 'Job Website' value
counts = df['Job Website'].value_counts()

# Create a pie chart using Plotly Express
fig = px.pie(
    counts,
    values=counts.values,
    names=counts.index,
    title='Job Websites'
)

# Show the chart
fig.show()