# -*- coding: utf-8 -*-
"""Top Skills By Site

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gO25bJEhNsghqE8NKoWVLSwRAGoRTePz
"""

#Top Skills by Site

import pandas as pd
from collections import Counter
import plotly.graph_objs as go
import plotly.express as px

filename = 'Combined_Version_2.csv'
data = pd.read_csv(filename)


df = pd.DataFrame(data)



df2 = df.query("`Job Website` == 'Indeed'")
df2 = df2[df['Skills'].notnull()]
df2 = df2['Skills'].str.split(',').explode('Skills').value_counts().head(20)
#print(df2)

fig = px.bar(df2, labels={}, title ="Indeed Top Skills")


df3 = df.query("`Job Website` == 'dice.com'")
df3 = df3[df['Skills'].notnull()]
df3 = df3['Skills'].str.split(',').explode('Skills').value_counts().head(20)
#print(df3)

fig2 = px.bar(df3, title ="Dice Top Skills")


df4 = df.query("`Job Website` == 'SimplyHired'")
df4 = df4[df['Skills'].notnull()]
df4 = df4['Skills'].str.split(',').explode('Skills').value_counts().head(20)
#print(df3)

fig3 = px.bar(df4, title ="Simply Hired Top Skills")

fig.show()
fig2.show()
fig3.show()