# -*- coding: utf-8 -*-
"""Top Companies By Openings

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17wy4xIRj0h6Bid-QUf9RPolVhjlRUBi4
"""

import pandas as pd
import plotly.graph_objs as go

df = pd.read_csv('Combined_Version_3.csv')

# Group the data by 'Company' and count the number of entries
company_counts = df['Company Name'].value_counts().head(15)

# Extract the company names and counts in reverse order
company_names = company_counts.index[::-1]
entry_counts = company_counts.values[::-1]

# Create the bar trace
bar_trace = go.Bar(
    x=entry_counts,
    y=company_names,
    orientation='h',  # Set orientation to horizontal
    marker_color='orchid',  # Set marker color
)

# Create the figure and add the bar trace
fig = go.Figure()
fig.add_trace(bar_trace)

# Update the layout as desired
fig.update_layout(
    xaxis_title='Number of Entries',
    yaxis_title='Company',
    title='<b>Top 15 Companies with the Most Openings</b>',  # Bold and center the title
    bargap=0.2,  # Set the gap between bars
    plot_bgcolor='rgb(153, 201, 69)'
)

# Show the figure
fig.show()